//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnRight;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Locomotion
        {
            get
            {
                return SteamVR_Actions.default_Locomotion;
            }
        }
        
        public virtual SteamVR_Action_Boolean Jump
        {
            get
            {
                return SteamVR_Actions.default_Jump;
            }
        }
        
        public virtual SteamVR_Action_Boolean CollectNearby
        {
            get
            {
                return SteamVR_Actions.default_CollectNearby;
            }
        }
        
        public virtual SteamVR_Action_Boolean Action
        {
            get
            {
                return SteamVR_Actions.default_Action;
            }
        }
        
        public virtual SteamVR_Action_Boolean GunInteract
        {
            get
            {
                return SteamVR_Actions.default_GunInteract;
            }
        }
        
        public virtual SteamVR_Action_Boolean GunInteract2
        {
            get
            {
                return SteamVR_Actions.default_GunInteract2;
            }
        }
        
        public virtual SteamVR_Action_Boolean GunInteract3
        {
            get
            {
                return SteamVR_Actions.default_GunInteract3;
            }
        }
        
        public virtual SteamVR_Action_Boolean GunInteractLongpress
        {
            get
            {
                return SteamVR_Actions.default_GunInteractLongpress;
            }
        }
        
        public virtual SteamVR_Action_Boolean SwapHandedness
        {
            get
            {
                return SteamVR_Actions.default_SwapHandedness;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
